# This playbook installs and configures essential tools for a Fish shell environment on Arch Linux.
# It covers:
# - Core utilities: fish, neovim, htop, btop, tmux, fzf, fd, ripgrep
# - Nerd fonts: ttf-hack-nerd, ttf-noto-nerd
# - Fish shell configuration: copies config.fish from Shared
# - NeoVim setup: installs Lazy.nvim and copies core.lua from Shared
# - Tmux setup: installs TPM and copies .tmux.conf from Shared
# - Fish plugin managers: installs Fisher and nvm.fish
---
- hosts: localhost
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Update packages (slow)
      pacman:
        name: fish,neovim,htop,btop,tmux,fzf,fd,ripgrep,pyenv
        state: present
        update_cache: yes
      become: true
    - pacman:
        name: ttf-hack-nerd,ttf-noto-nerd
        state: present
      become: true

    - name: Setup Fish shell
      file:
        src: "{{ playbook_dir | dirname }}/Shared/config.fish"
        path: ~/.config/fish/config.fish
        state: link
        force: true
    - stat: # Keep all sensitive environment variables for Fish shell in this file
        path: ../Nonesharable/secrets.config.fish
      register: fish_secrets_file
    - file:
        src: "{{ playbook_dir | dirname }}/Nonesharable/secrets.config.fish"
        path: ~/.config/fish/conf.d/secrets.config.fish
        state: link
        force: true
      when: fish_secrets_file.stat.exists

    - name: Setup NeoVim/LazyVim
      stat:
        path: ~/.config/nvim
      register: lazynvim_dir
    - git:
        repo: https://github.com/LazyVim/starter
        dest: ~/.config/nvim
        depth: 1
      when: not lazynvim_dir.stat.exists
    - file:
        path: ~/.config/nvim/.git
        state: absent
    - file:
        src: "{{ playbook_dir | dirname }}/Shared/nvim-core.lua"
        path: ~/.config/nvim/lua/plugins/core.lua
        state: link
        force: true

    - name: Setup Tmux
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        depth: 1
    - file:
        src: "{{ playbook_dir | dirname }}/Shared/.tmux.conf"
        path: ~/.tmux.conf
        state: link
        force: true
    - stat: # Add your Tmux custom into this file
        path: ../Nonesharable/tmux_default.conf
      register: optional_tmux_file
    - file:
        path: "~/.config/tmux"
        state: directory
        mode: "0755"
    - file:
        src: "{{ playbook_dir | dirname }}/Nonesharable/tmux_default.conf"
        path: "~/.config/tmux/default.conf"
        state: link
        force: true
      when: optional_tmux_file.stat.exists

    # Some other alternative on Fish shell
    - name: Install Fisher plugin manager
      ansible.builtin.shell: |
        curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
      args:
        executable: /usr/bin/fish
    - name: Install Node Version Manager
      ansible.builtin.shell: |
        fisher install jorgebucaran/nvm.fish
      args:
        executable: /usr/bin/fish
