# This playbook installs and configures essential tools for a Fish shell environment on Arch Linux.
# It covers:
# - Core utilities: fish, neovim, htop, btop, tmux, fzf, fd, ripgrep
# - Nerd fonts: ttf-hack-nerd, ttf-noto-nerd
# - Fish shell configuration: copies config.fish from Shared
# - NeoVim setup: installs Lazy.nvim and copies core.lua from Shared
# - Tmux setup: installs TPM and copies .tmux.conf from Shared
# - Fish plugin managers: installs Fisher and nvm.fish
---
- hosts: localhost
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - pacman:
        name: fish,neovim,htop,btop,tmux,fzf,fd,ripgrep
        state: present
        update_cache: yes
      become: true
    - pacman:
        name: ttf-hack-nerd,ttf-noto-nerd
        state: present
      become: true

    - name: check if Fish config exists
      stat:
        path: ~/.config/fish/config.fish
      register: fish_config_file
    - name: Copy Fish config
      copy:
        src: ../Shared/config.fish
        dest: ~/.config/fish/config.fish
        create_parents: yes
      when: not fish_config_file.stat.exists

    - name: Check if Lazy.nvim exists
      stat:
        path: ~/.config/nvim
      register: lazynvim_dir
    - name: Download Lazy.nvim
      git:
        repo: https://github.com/LazyVim/starter
        dest: ~/.config/nvim
        depth: 1
      when: not lazynvim_dir.stat.exists
    - name: Clean up Lazy.nvim
      file:
        path: ~/.config/nvim/.git
        state: absent
    - name: Clheck if NeoVim config exists
      stat:
        path: ~/.config/nvim/lua/plugins/core.lua
      register: nvim_config_file
    - name: Copy NeoVim config
      copy:
        src: ../Shared/nvim-core.lua
        dest: ~/.config/nvim/lua/plugins/core.lua
      when: not nvim_config_file.stat.exists

    - name: Install Tmux TMP plugins manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        depth: 1
    - name: Copying Tmux configuration
      copy:
        src: ../Shared/.tmux.conf
        dest: ~/.tmux.conf

    - name: Install Fisher plugin manager
      ansible.builtin.shell: |
        curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
      args:
        executable: /usr/bin/fish
    - name: Install Node Version Manager
      ansible.builtin.shell: |
        fisher install jorgebucaran/nvm.fish
      args:
        executable: /usr/bin/fish
