# This playbook sets up a basic Fish Shell for a development environment on macOS, including:
# - Installs essential CLI tools like fish, neovim, htop, btop, tmux, fzf, fd, ripgrep, pyenv using Homebrew.
# - Installs powerline fonts for a better terminal experience.
# - Configures Fish shell with a shared configuration and extra settings.
# - Sets up Lazy.nvim for Neovim configuration.
# - Installs and configures Tmux with a shared configuration.
# - Installs Fisher plugin manager for Fish shell.
# - Installs Node Version Manager (nvm.fish) for Fish shell.
---
- hosts: localhost
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - homebrew:
        name: fish,neovim,htop,btop,tmux,fzf,fd,ripgrep,pyenv
        state: present
        update_homebrew: yes
    - homebrew_cask:
        name: font-powerline-symbols,font-consolas-for-powerline,font-fira-mono-for-powerline,font-noto-mono-for-powerline,font-hack-nerd-font
        state: present

    - name: Check if Fish config exists
      stat:
        path: ~/.config/fish/config.fish
      register: fish_config_file
    - name: Copy Fish config
      copy:
        src: ../Shared/config.fish
        dest: ~/.config/fish/config.fish
        create_parents: yes
      when: not fish_config_file.stat.exists
    - name: Copy Fish extra config
      copy:
        src: extra.config.fish
        dest: ~/.config/fish/conf.d/extra.config.fish
        create_parents: yes

    - name: Check if Lazy.nvim exists
      stat:
        path: ~/.config/nvim
      register: lazynvim_dir
    - name: Download Lazy.nvim
      git:
        repo: https://github.com/LazyVim/starter
        dest: ~/.config/nvim
        depth: 1
      when: not lazynvim_dir.stat.exists
    - name: Clean up Lazy.nvim
      file:
        path: ~/.config/nvim/.git
        state: absent
    - name: Copy NeoVim config
      copy:
        src: ../share/nvim-core.lua
        dest: ~/.config/nvim/lua/plugins/core.lua

    - name: Install Tmux TMP plugins manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        depth: 1
    - name: Copying Tmux configuration
      copy:
        src: ../Shared/.tmux.conf
        dest: ~/.tmux.conf

    - name: Install Fisher plugin manager
      ansible.builtin.shell: |
        curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
      args:
          executable: /opt/homebrew/bin/fish
    - name: Install Node Version Manager
      ansible.builtin.shell: |
        fisher install jorgebucaran/nvm.fish
      args:
        executable: /opt/homebrew/bin/fish

