# This playbook sets up a basic Fish Shell for a development environment on macOS, including:
# - Installs essential CLI tools like fish, neovim, htop, btop, tmux, fzf, fd, ripgrep, pyenv using Homebrew.
# - Installs powerline fonts for a better terminal experience.
# - Configures Fish shell with a shared configuration and extra settings.
# - Sets up Lazy.nvim for Neovim configuration.
# - Installs and configures Tmux with a shared configuration.
# - Installs Fisher plugin manager for Fish shell.
# - Installs Node Version Manager (nvm.fish) for Fish shell.
---
- hosts: localhost
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"
  tasks:
    - homebrew:
        name: fish,neovim,htop,btop,tmux,fzf,fd,ripgrep,pyenv
        state: present
        update_homebrew: yes
      when: should_update_os | default(false) | bool
    - homebrew_cask:
        name: font-powerline-symbols,font-consolas-for-powerline,font-fira-mono-for-powerline,font-noto-mono-for-powerline,font-hack-nerd-font
        state: present
      when: should_update_os | default(false) | bool

    - name: Setup Fish shell
      file:
        src: "{{ playbook_dir | dirname }}/Shared/config.fish"
        path: ~/.config/fish/config.fish
        state: link
        force: true
    - name: Copy Fish config
      copy:
        src: ../Shared/config.fish
        dest: ~/.config/fish/config.fish
        create_parents: yes
      when: not fish_config_file.stat.exists
    - name: Copy Fish extra config
      copy:
        src: extra.config.fish
        dest: ~/.config/fish/conf.d/extra.config.fish
        create_parents: yes
    - stat: # Keep all sensitive environment variables for Fish shell in this file
        path: ../Nonesharable/secrets.config.fish
      register: fish_secrets_file
    - file:
        src: "{{ playbook_dir | dirname }}/Nonesharable/secrets.config.fish"
        path: ~/.config/fish/conf.d/secrets.config.fish
        state: link
        force: true
      when: fish_secrets_file.stat.exists
    - file:
        src: "{{ playbook_dir | dirname }}/Shared/starship.toml"
        path: ~/.config/starship.toml
        state: link
        force: true

    - name: Setup NeoVim/LazyVim
      stat:
        path: ~/.config/nvim
      register: lazynvim_dir
    - git:
        repo: https://github.com/LazyVim/starter
        dest: ~/.config/nvim
        depth: 1
      when: not lazynvim_dir.stat.exists
    - file:
        path: ~/.config/nvim/.git
        state: absent
    - file:
        src: "{{ playbook_dir | dirname }}/Shared/nvim-core.lua"
        path: ~/.config/nvim/lua/plugins/core.lua
        state: link
        force: true

    - name: Setup Tmux
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        depth: 1
    - file:
        src: "{{ playbook_dir | dirname }}/Shared/.tmux.conf"
        path: ~/.tmux.conf
        state: link
        force: true
    - stat: # Add your Tmux custom into this file
        path: ../Nonesharable/tmux_default.conf
      register: optional_tmux_file
    - file:
        path: "~/.config/tmux"
        state: directory
        mode: "0755"
    - file:
        src: "{{ playbook_dir | dirname }}/Nonesharable/tmux_default.conf"
        path: "~/.config/tmux/default.conf"
        state: link
        force: true
      when: optional_tmux_file.stat.exists

    - name: Install Fisher plugin manager
      ansible.builtin.shell: |
        curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
      args:
          executable: /opt/homebrew/bin/fish
    - name: Install Node Version Manager
      ansible.builtin.shell: |
        fisher install jorgebucaran/nvm.fish
      args:
        executable: /opt/homebrew/bin/fish
    - name: Install Fzf search
      ansible.builtin.shell: |
        fisher install jethrokuan/fzf
      args:
        executable: /usr/bin/fish
