---
- hosts: localhost
  connection: local
  remote_user: liam
  tasks:
    - homebrew:
        name: fish,neovim,htop,btop,tmux,fzf,fd,ripgrep,pyenv
        state: present
        update_homebrew: yes
    - homebrew_cask:
        name: font-powerline-symbols,font-consolas-for-powerline,font-fira-mono-for-powerline,font-noto-mono-for-powerline,font-hack-nerd-font
        state: present
    - name: Copy Fish config
      copy:
        src: config.fish
        dest: ~/.config/fish/config.fish
    - name: Check if Lazy.nvim exists
      stat:
        path: ~/.config/nvim
      register: lazynvim_dir
    - name: Download Lazy.nvim
      git:
        repo: https://github.com/LazyVim/starter
        dest: ~/.config/nvim
        depth: 1
      when: not lazynvim_dir.stat.exists
    - name: Clean up Lazy.nvim
      file:
        path: ~/.config/nvim/.git
        state: absent
    - name: Install Tmux TMP plugins manager
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        depth: 1
    - name: Copying Tmux configuration
      copy:
        src: .tmux.conf
        dest: ~/.tmux.conf
    - name: Install Node Version Manager
      homebrew:
        name: nvm
        state: present
